# .travis.yml for r-travis.
#
# If you're looking to use r-travis with your project, DO NOT USE THIS
# FILE -- use `sample.travis.yml` instead.

#TODO(petrifast): Uncomment the "language: objective-c" line and comment out the "language: c" line + the tmux line below to build on OSX
#language: c
language: objective-c

script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - cp scripts/travis-tool.sh fakepackage
  - cd fakepackage
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  #  TODO(petrifast): comment out the next line (tmux) from an OS X build
  # - ./travis-tool.sh aptget_install tmux
  - ./travis-tool.sh github_package assertthat
  - ./travis-tool.sh github_package testthat
