# THIS FILE IS STILL A TEST

language: c
script: R CMD check . 
before_script:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - ./travis-tool bootstrap
  - ./travis-tool github_package assertthat
  - ./travis-tool install_deps
